apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config
data:
  config.yaml: |
    mutation:
      pods:
      - name: sapcc-operator-*
        enabled: true
        annotations: {}
        labels: {}
        containerreplacements:
          sapcc-operator: columbus.common.repositories.cloud.sap/com.sap.edgelm/sapcc-operator:0.59.0-test-latest
      - name: cleanup-cluster-*
        enabled: false
        annotations: {}
        labels: {}
        containerreplacements:
          cleanup: columbus.common.repositories.cloud.sap/com.sap.edgelm/docker-cleanup-cluster:0.35.0-test-latest
      - name: edge-monitoring-service-kube-state-metrics-*
        enabled: true
        containerreplacements:
          kube-state-metrics: columbus.common.repositories.cloud.sap/com.sap.edgelm/kube-state-metrics:latest
      - name: edge-monitoring-service-pr-operator-*
        enabled: true
        containerreplacements:
          prometheus-operator: columbus.common.repositories.cloud.sap/com.sap.edgelm/prometheus-operator:0.45.0-test.i330716-latest
      - name: edge-monitoring-service-prometheus-node-exporter-*
        enabled: true
        containerreplacements:
          node-exporter: columbus.common.repositories.cloud.sap/com.sap.edgelm/node-exporter:latest
      - name: prometheus-edge-monitoring-service-pr-prometheus-0
        enabled: true
        containerreplacements:
          prometheus: columbus.common.repositories.cloud.sap/com.sap.edgelm/prometheus:2.54.14-test.i330716-latest
          config-reloader: columbus.common.repositories.cloud.sap/com.sap.edgelm/prometheus-config-reloader:0.45.0-test.i330716-latest
          thanos-sidecar: columbus.common.repositories.cloud.sap/com.sap.edgelm/thanos:latest