apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-config
data:
  config.yaml: |
    mutation:
      pods:
      - name: sapcc-operator-*
        enabled: true
        annotations: {}
        labels: {}
        containerreplacements:
          sapcc-operator: columbus.common.repositories.cloud.sap/com.sap.edgelm/sapcc-operator:0.59.0-test.i330716-latest
      - name: cleanup-cluster-*
        enabled: false
        annotations: {}
        labels: {}
        containerreplacements:
          cleanup: columbus.common.repositories.cloud.sap/com.sap.edgelm/docker-cleanup-cluster:0.35.0-test.i330716-latest